# This file should contain by the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

        Car.find_by(model: 'Model 3').car_categories.create([{name: 'Car'}, {name: 'Electric'}, {name: 'Fuel Saver'}])
        Car.find_by(model: 'R8').car_categories.create([{name: 'Sport'}, {name: 'Car'}, {name: 'Exotic'}])
        Car.find_by(model: 'Accord').car_categories.create([{name: 'Car'}])
        Car.find_by(model: 'Jetta').car_categories.create([{name: 'Car'}, {name: 'Fuel Saver'}])
        Car.find_by(model: 'Altima').car_categories.create([{name: 'Car'}])
        Car.find_by(model: 'Chbyenger').car_categories.create([{name: 'Sport'}, {name: 'Car'}])
        Car.find_by(model: 'ATS').car_categories.create([{name: 'Car'}, {name: 'Sport'}])
        Car.find_by(model: 'Q7').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'Stelvio').car_categories.create([{name: 'Car'}, {name: 'Exotic'}])
        Car.find_by(model: 'Fusion').car_categories.create([{name: 'Car'}, {name: 'Fuel Saver'}])
        Car.find_by(model: 'FJ Cruiser').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'Wrangler Unlimited').car_categories.create([{name: 'Truck'}, {name: 'Sport'}])
        Car.find_by(model: '4Runner').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'Suburban').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'Corvette').car_categories.create([{name: 'Sport'}, {name: 'Car'}, {name: 'Exotic'}])
        Car.find_by(model: 'Corolla').car_categories.create([{name: 'Car'}, {name: 'Fuel Saver'}])
        Car.find_by(model: 'Tucson').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'Rio').car_categories.create([{name: 'Car'}, {name: 'Fuel Saver'}])
        Car.find_by(model: 'Tundra').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'Pa{namera').car_categories.create([{name: 'Sport'}, {name: 'Car'}, {name: 'Exotic'}])
        Car.find_by(model: 'C-HR').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'C 10 super cheyenne').car_categories.create([{name: 'Truck'}])
        Car.find_by(model: 'Model Y').car_categories.create([{name: 'Car'}, {name: 'Family'}, {name: 'Electric'}, {name: 'Fuel Saver'}])
        Car.find_by(model: '300').car_categories.create([{name: 'Car'}])
        Car.find_by(model: 'Town Car').car_categories.create([{name: 'Car'}, {name: 'Family'}])
        Car.find_by(model: 'ILX').car_categories.create([{name: 'Car'}])
        Car.find_by(model: '911').car_categories.create([{name: 'Sport'}, {name: 'Car'}, {name: 'Exotic'}])
        Car.find_by(model: 'Accent').car_categories.create([{name: 'Car'}, {name: 'Fuel Saver'}])
        Car.find_by(model: 'Sien{na').car_categories.create([{name: 'Sport'}, {name: 'Car'}, {name: 'Exotic'}])
        Car.find_by(model: 'C-Class').car_categories.create([{name: 'Sport'}, {name: 'Car'}])
        Car.find_by(model: 'G-Class').car_categories.create([{name: 'Truck'}, {name: 'Exotic'}])        